#ifndef TABOULE_RAZA_OBJECT_TYPE_H
#define TABOULE_RAZA_OBJECT_TYPE_H


#define GOP_CONNECT 400
#define GOP_DISCONNECT 401
#define GOP_GAME_SAVE 402
#define GOP_ASK_SAVE 403

#define GOP_BUILD 410
#define GOP_DELETE 411
#define GOP_RISK 412

#define GOP_UPDATE_W 420
#define GOP_SPAWN_W 421
#define GOP_DELETE_W 422

#define DELEGATE 499

#define C_COMMAND 65535

#endif //TABOULE_RAZA_OBJECT_TYPE_H
